### ISSUE TITLE
Just noticed your project

### ISSUE THREAD

**Issue by kof** [motion/gloss#3]
I think some of things you implement are part of https://github.com/cssinjs/jss/issues/356
Some of them and more are implemented by jss-expand and react-jss

Maybe you are interested in helping adding and improving things in JSS repositories, feel free to reach out on gitter!

**Comment by natew** [comment]
jss-expand is cool, it should expose it's expansions more generically so people can use it outside JSS, no need to tie it into the plugin API (motion-nice-styles is like this).

react-jss seems ok, but verbose for my liking and also requires you put styles before your views which is a pattern I don't follow.

Tbh, gloss came before a lot of the jss stuff, and I'm happy with how it works. To get all the functionality we have you have to sort of remove flexibility. For example, expansions within dynamic themes, requires quite a bit of integration.

The more the merrier though! If JSS gets to where gloss is, I'd gladly switch. I'll certainly crib some of the expansions from jss-expand (I've been wanting to implement a couple for a while). Though I think nice-styles has faster loops.

I see gloss as higher level than JSS. JSS is a great toolkit, but doesn't make big choices, and so can't have some of the cool but maybe controversial features.

I think they have big upsides though. One weekend I'm going to hack in some of my babel-fu and have all your static styles be completely optimized (compiled with motion-nice-style beforehand, maybe even run it through JSS and just hardcode the output styles). We did this previously in a different project, and it was awesome.

**Comment by kof** [comment]
> jss-expand is cool, it should expose it's expansions more generically so people can use it outside JSS, no need to tie it into the plugin API (motion-nice-styles is like this).

I am more than happy to extract those things into a separate, generic library.

> react-jss seems ok, but verbose for my liking and also requires you put styles before your views which is a pattern I don't follow.

We can discuss what things you want and don't and find a solution. Also take a look at  [jss-theme-reactor](https://github.com/nathanmarks/jss-theme-reactor) which is used by material-ui next branch. Also if your solution is much different than the others, its fine to keep it as it is and I would just add it to the links for integrations after I understand more the ideas behind it.

>  For example, expansions within dynamic themes, requires quite a bit of integration.

My next task is to introduce  a way for more efficient dynamic themes:
https://github.com/cssinjs/jss/issues/356

> I see gloss as higher level than JSS.

Yep, thats the idea for JSS, to stay lower level and less opinionated.

> I think they have big upsides though. One weekend I'm going to hack in some of my babel-fu and have all your static styles be completely optimized (compiled with motion-nice-style beforehand, maybe even run it through JSS and just hardcode the output styles). We did this previously in a different project, and it was awesome.

Lets talk about this things in separate issues or/and gitter. I would love to work with you on all this!

**Comment by kof** [comment]
Btw. I have started to gather a list of products/companies using JSS http://cssinjs.org/we-are-using , do you have one to add?

**Comment by natew** [comment]
Awesome! Look forward to collaborating. When I worked on [reapp](https://github.com/reapp/reapp), specifically the theme engine, I worked with the material guys on some of that.

Also, pulled some stuff out of our stack as a better demo: https://github.com/motion/gloss-demo

And sure, we are in stealth still, but you can add the (slightly broken) website: https://seemirai.com
